### PR TITLE
Enhance optimize-windows-update.ps1

### PR DESCRIPTION
**Pull request by bgraeb**
icacls shouldn't break with non-english images

### CODE REVIEW

**Comment by StefanScherer** [comment]
Thanks. Nice trick to translate the user name.
Do you want to send a PR to the upstream repo [W4RH4WK/Debloat-Windows-10](https://github.com/W4RH4WK/Debloat-Windows-10) as well?

**Comment by StefanScherer** [comment]
I had this error in a windows_10 build today:

```
    vmware-iso: Optimize Windows Update
    vmware-iso: At C:\Users\vagrant\AppData\Local\Temp\Debloat-Windows-10-master\scripts\optimize-windows-update.ps1:26 char:58
    vmware-iso: + ... acls "$env:WinDIR\System32\MusNotification.exe" /deny "$EveryOne:(X)"
    vmware-iso: +                                                            ~~~~~~~~~~
    vmware-iso: Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to
    vmware-iso: delimit the name.
    vmware-iso: At C:\Users\vagrant\AppData\Local\Temp\Debloat-Windows-10-master\scripts\optimize-windows-update.ps1:28 char:60
    vmware-iso: + ... ls "$env:WinDIR\System32\MusNotificationUx.exe" /deny "$EveryOne:(X)"
    vmware-iso: +                                                            ~~~~~~~~~~
    vmware-iso: Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to
    vmware-iso: delimit the name.
    vmware-iso:     + CategoryInfo          : ParserError: (:) [], ParseException
    vmware-iso:     + FullyQualifiedErrorId : InvalidVariableReferenceWithDrive
    vmware-iso:
```

Any ideas what we can improve here?

**Comment by bgraeb** [comment]
We need to wrap the variables in the string expressions with parentheses, to prevent interpretation of the ":" as part of the variable:

`icacls "$env:WinDIR\System32\MusNotificationUx.exe" /deny "$EveryOne:(X)"`
to
`icacls "$env:WinDIR\System32\MusNotificationUx.exe" /deny "$($EveryOne):(X)"`

**Comment by StefanScherer** [comment]
Thanks. Fixed with #2

**Pull request merged**
